name: lizard-producto-prod

services:
  postgres-producto:
    image: postgres:16-alpine
    container_name: lizard-postgres-producto
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - lizard_producto_data:/var/lib/postgresql/data
    ports:
      - "25433:5432"
    networks:
      - lizard-producto-int

  producto-ms:
    build: .
    container_name: lizard-producto-ms
    restart: unless-stopped
    depends_on:
      postgres-producto:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: lizard-postgres-producto
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./logs:/app/logs
    networks:
      - lizard-producto-int
      - lizard-prod-net

volumes:
  lizard_producto_data:

networks:
  lizard-prod-net:
    external: true
    name: lizard-prod-net
  lizard-producto-int:
    name: lizard-producto-int
