name: lizard-carrito-dev

services:
  postgres-carrito-dev:
    image: postgres:16-alpine
    container_name: lizard-postgres-carrito-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: lizard_carrito_db
      POSTGRES_USER: lizard
      POSTGRES_PASSWORD: lizard
    ports:
      - "15437:5432"
    volumes:
      - lizard_carrito_dev_data:/var/lib/postgresql/data

volumes:
  lizard_carrito_dev_data:
