ALTER TABLE productos
    ADD COLUMN IF NOT EXISTS sku VARCHAR(50),
    ADD COLUMN IF NOT EXISTS precio NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stock INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE productos SET sku = CONCAT('SKU-', id) WHERE sku IS NULL;

ALTER TABLE productos ALTER COLUMN sku SET NOT NULL;
ALTER TABLE productos ADD CONSTRAINT uk_productos_sku UNIQUE (sku);
